# Generated by Django 3.2.18 on 2023-06-07 20:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_testimonial_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='testimonial',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='user',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonial',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
