# Generated by Django 3.2.18 on 2023-06-07 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20230607_2124'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
