# Generated by Django 3.2.18 on 2023-06-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
