# Generated by Django 3.2.18 on 2023-06-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(choices=[('5X7', '5x7'), ('8X10', '8x10'), ('12X18', '12x18'), ('18X24', '18x24'), ('24X36', '24x36')], max_length=5),
        ),
    ]
